// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "operationId": "login",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Login"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "get": {
                "tags": [
                    "auth"
                ],
                "operationId": "logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Logout"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh-token": {
            "post": {
                "tags": [
                    "auth"
                ],
                "operationId": "refreshToken",
                "parameters": [
                    {
                        "description": "Refresh token req",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.RefreshToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.RefreshToken"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "tags": [
                    "auth"
                ],
                "operationId": "register",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.Register"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.Register"
                        }
                    }
                }
            }
        },
        "/api/v1/batch": {
            "get": {
                "tags": [
                    "batch"
                ],
                "operationId": "getAllBatches",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.GetAllBatches"
                        }
                    }
                }
            }
        },
        "/api/v1/class": {
            "get": {
                "tags": [
                    "class"
                ],
                "operationId": "getAllClasses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.GetAllClasses"
                        }
                    }
                }
            }
        },
        "/api/v1/class_majors/batch/{batch_id}": {
            "get": {
                "tags": [
                    "classMajor"
                ],
                "operationId": "getAllClassMajors",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Batch ID",
                        "name": "batch_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.GetAllClassMajors"
                        }
                    }
                }
            }
        },
        "/api/v1/excel/import": {
            "post": {
                "tags": [
                    "excel"
                ],
                "operationId": "importData",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/majors/batch/{batch_id}": {
            "get": {
                "tags": [
                    "major"
                ],
                "operationId": "getAllMajors",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Batch ID",
                        "name": "batch_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.GetAllMajors"
                        }
                    }
                }
            }
        },
        "/api/v1/student": {
            "get": {
                "tags": [
                    "student"
                ],
                "operationId": "getAllStudents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responses.GetAllStudents"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Batch": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.Class": {
            "type": "object",
            "required": [
                "id",
                "major",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "major": {
                    "$ref": "#/definitions/dto.Major"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.Major": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.Student": {
            "type": "object",
            "required": [
                "id",
                "name",
                "nis"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "nis": {
                    "type": "string"
                }
            }
        },
        "requests.Login": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "default": "email@email.com"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "requests.RefreshToken": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "requests.Register": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "default": "email@email.com"
                },
                "name": {
                    "type": "string",
                    "default": "John Doe"
                },
                "password": {
                    "type": "string",
                    "default": "password"
                }
            }
        },
        "responses.GetAllBatches": {
            "type": "object",
            "required": [
                "batches"
            ],
            "properties": {
                "batches": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Batch"
                    }
                }
            }
        },
        "responses.GetAllClassMajors": {
            "type": "object",
            "required": [
                "classes"
            ],
            "properties": {
                "classes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Class"
                    }
                }
            }
        },
        "responses.GetAllClasses": {
            "type": "object",
            "required": [
                "classes"
            ],
            "properties": {
                "classes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Class"
                    }
                }
            }
        },
        "responses.GetAllMajors": {
            "type": "object",
            "required": [
                "majors"
            ],
            "properties": {
                "majors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Major"
                    }
                }
            }
        },
        "responses.GetAllStudents": {
            "type": "object",
            "required": [
                "students"
            ],
            "properties": {
                "students": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Student"
                    }
                }
            }
        },
        "responses.Login": {
            "type": "object",
            "required": [
                "access_token",
                "refresh_token"
            ],
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "responses.Logout": {
            "type": "object"
        },
        "responses.RefreshToken": {
            "type": "object",
            "required": [
                "access_token",
                "refresh_token"
            ],
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "responses.Register": {
            "type": "object",
            "required": [
                "access_token",
                "refresh_token"
            ],
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "PresensiGo API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
