definitions:
  requests.LoginRequest:
    properties:
      email:
        default: email@email.com
        type: string
      password:
        type: string
    type: object
  requests.RegisterRequest:
    properties:
      email:
        default: email@email.com
        type: string
      name:
        default: John Doe
        type: string
      password:
        default: password
        type: string
    type: object
  responses.LoginResponse:
    properties:
      access_token:
        type: string
      token:
        type: string
    type: object
  responses.RegisterResponse:
    properties:
      access_token:
        type: string
      token:
        type: string
    type: object
info:
  contact: {}
  title: Presensi Sekolah API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      operationId: Login
      parameters:
      - description: Login request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.LoginResponse'
      tags:
      - auth
  /api/v1/auth/register:
    post:
      operationId: Register
      parameters:
      - description: Login request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.RegisterRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.RegisterResponse'
      tags:
      - auth
  /api/v1/excel/import:
    post:
      operationId: Import
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - excel
swagger: "2.0"
