definitions:
  dto.Batch:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  requests.Login:
    properties:
      email:
        default: email@email.com
        type: string
      password:
        type: string
    type: object
  requests.Register:
    properties:
      email:
        default: email@email.com
        type: string
      name:
        default: John Doe
        type: string
      password:
        default: password
        type: string
    type: object
  responses.GetAllBatches:
    properties:
      batches:
        items:
          $ref: '#/definitions/dto.Batch'
        type: array
    type: object
  responses.Login:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  responses.Logout:
    type: object
  responses.Register:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
info:
  contact: {}
  title: PresensiGo API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      operationId: Login
      parameters:
      - description: Login request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Login'
      tags:
      - auth
  /api/v1/auth/logout:
    get:
      operationId: Logout
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Logout'
      tags:
      - auth
  /api/v1/auth/register:
    post:
      operationId: Register
      parameters:
      - description: Login request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.Register'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Register'
      tags:
      - auth
  /api/v1/batch:
    get:
      operationId: getAllBatches
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.GetAllBatches'
      tags:
      - batch
  /api/v1/excel/import:
    post:
      operationId: Import
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - excel
swagger: "2.0"
